baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'George Sequeira'
theme = "archie"
paginate=3 # articles per page
copyright = "©George Sequeira"

[permalinks]
posts = "/writing/:title/"

[params]
    favicon = "favicon.ico"
	customcss = ["css/custom.css"]
	mode="auto"
	useCDN=false

[[menu.main]]
name = "Posts"
url = "/writing"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
