baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'George Sequeira'
theme = "archie"
paginate=3 # articles per page
copyright = "©George Sequeira"

[permalinks]
posts = "/writing/:title/"

[params]
	customcss = ["css/custom.css"]
	mode="auto"
	useCDN=false
	subtitle = "👋 Hey folks! I’m George Sequeira. I’m a technology entrepreneur, investor, advisor currently on hiatus."

[[menu.main]]
name = "Posts"
url = "/writing"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
