baseURL = 'https://www.georgesequeira.com/'
languageCode = 'en-us'
title = 'George Sequeira'
theme = "archie"
paginate=3 # articles per page
copyright = "©George Sequeira"
googleAnalytics = 'G-N927GRKWX9'

[permalinks]
posts = "/writing/:title/"



[params]
    favicon = "/img/favicon.png"
	customcss = ["css/custom.css"]
	mode="auto"
	useCDN=true

[[menu.main]]
name = "Posts"
url = "/writing"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
